Add PGENV_SCRIPT_PRESTOP.
I realized that usually what you want to execute against a database
is something that involves connecting to the database itself.
Therefore I added the capability to execute a script *before*
the instance is stopped.
The script is protected against failures, so that it does not affect
the pgenv workflow.

diff --git a/bin/pgenv b/bin/pgenv
--- a/bin/pgenv
+++ b/bin/pgenv
@@ -475,6 +475,7 @@ pgenv_configuration_write() {
 
     pgenv_configuration_write_variable "$CONF" "PGENV_SCRIPT_POSTINSTALL" "" 'Script to execute when the build process finishes'
     pgenv_configuration_write_variable "$CONF" "PGENV_SCRIPT_POSTINITDB" "" 'Script to execute when initdb finishes'
+    pgenv_configuration_write_variable "$CONF" "PGENV_SCRIPT_PRESTOP" "" 'Script to execute before the cluster stops'
     pgenv_configuration_write_variable "$CONF" "PGENV_SCRIPT_POSTSTOP" "" 'Script to execute when the cluster has been stopped'
     pgenv_configuration_write_variable "$CONF" "PGENV_SCRIPT_POSTSTART" "" 'Script to execute when the cluster has been started'
     pgenv_configuration_write_variable "$CONF" "PGENV_SCRIPT_POSTRESTART" "" 'Script to execute when the cluster has been restarted'
@@ -644,11 +645,23 @@ pgenv_stop_or_restart_instance(){
     local command=$1
     local v=$2
 
+    # Don't exit on error.
+    trap "" ERR
+
+
     if $PG_CTL status -D "$PG_DATA"  &> /dev/null; then
         # ok, server running, apply the command
         case $command in
             stop)
                 pgenv_debug "pg_ctl stopping with flags [$PGENV_STOP_OPTS]"
+
+
+                # if there is a pre-stop script to run, run it
+                if [ -x "$PGENV_SCRIPT_PRESTOP" ]; then
+                    echo "Running pre-stop script [$PGENV_SCRIPT_PRESTOP]"
+                    $PGENV_SCRIPT_PRESTOP "$PG_DATA" 
+                fi
+
                 $PG_CTL stop -D "$PG_DATA" $PGENV_STOP_OPTS &> /dev/null
                 echo "PostgreSQL $v stopped"
 
